### ISSUE TITLE
Fix dev build process

### ISSUE THREAD

**Issue by gandalfar** [DragonPyConf/dragonpy.com#22]
Right now editing HTML/CSS requires manual re-run of gulp and jekyll. Can we figure out so that everything can run in background and developer can just edit HTML and (S)CSS files?

**Comment by sparkica** [comment]
Working on it, might have something ready asap...

**Comment by gandalfar** [comment]
@sparkica what's your status on this? (so that I don't duplicate the work)

**Comment by gandalfar** [comment]
This was fixed in #42
