### ISSUE TITLE
PSF grant requirements

### ISSUE THREAD

**Issue by zupo** [DragonPyConf/dragonpy.com#41]
To be able to get a grant from the Python Software Foundation, [we need the following on our website](https://docs.google.com/document/d/19teTUyC8G3Q53g0FEHNFDZBNjUP16ivwc60MiPQl7pg/edit):
* [ ] a registration page showing how people will register
* [x] venue information
* [x]  a code of conduct listed on the registration page or workshop website
* [x] schedule
* [x] sponsor prospectus or sponsorship webpage on your conference website
* [x] information on what sponsorships your event has received already

The deadline to submit for a grant is 6 weeks before the event, this means beginning of March. Let's do it sooner rather than later.

**Comment by gandalfar** [comment]
@zupo Do you want to wait with registration page until we go live with the tickets?

**Comment by zupo** [comment]
Yes, I wouldn't do anything special with the registration page. I.e. just link to our pretix "shop" which should display all needed information.

**Comment by gandalfar** [comment]
This is live now, so closing this issue.
