### ISSUE TITLE
Add Qualimental as bronze sponsor

### ISSUE THREAD

**Issue by zupo** [DragonPyConf/dragonpy.com#50]
Logo: https://qualimental.co.uk/wp-content/uploads/2020/01/cropped-qualimental_logo_copy_small-1-2.png

Link to https://qualimental.co.uk/

**Comment by gandalfar** [comment]
Can you ask them for higher-quality logo?

**Comment by zupo** [comment]
They don't have it ATM, they'll send it when they do.

**Comment by JanLikar** [comment]
I can take care of this, if you want me to.
