### ISSUE TITLE
www. version of the site returns https error

### ISSUE THREAD

**Issue by gandalfar** [DragonPyConf/dragonpy.com#56]
Looks like github/dns issue

**Comment by zupo** [comment]
Works for me?

Which browser?

**Comment by gandalfar** [comment]
Open Chrome in incognito mode and visit www. twice, you'll get: NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by zupo** [comment]
Yep, have it now, thanks.

**Comment by zupo** [comment]
GitHub does not support this: https://github.community/t5/GitHub-Pages/Does-GitHub-Pages-Support-HTTPS-for-www-and-subdomains/m-p/7202#M495

**Comment by zupo** [comment]
Enabled Cloudflare proxy, which should support SSL on both apex and www addresses.

@gandalfar: try again pls.

**Comment by gandalfar** [comment]
Can't reproduce it anymore, thanks!
