### ISSUE TITLE
Add SmartNinja as supporter

### ISSUE THREAD

**Issue by zupo** [DragonPyConf/dragonpy.com#58]
Logo: https://storage.googleapis.com/smartninja/smartninja-logo-1547584690.png

**Comment by zupo** [comment]
@JanLikar: have a minute for this?

**Comment by zupo** [comment]
I'll do it.

**Comment by JanLikar** [comment]
Sorry, didn't see it. I can do it now, if you haven't started already.

**Comment by JanLikar** [comment]
Nevermind.
